import { useState } from 'react';
import Button from "../components/Button";
import Modal from "../components/Modal";

function ModalPage() {
    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    };

    const handleClose = () => {
        setShowModal(false);
    };

    const actionButton = <Button onClick={handleClose} primary>Accept</Button>;

    const modal = <Modal onClose={handleClose} actionBar={actionButton}>
        <p>Here is the conditions you need to accept!</p>
    </Modal>
    return (
        <div>
            < Button onClick={handleClick} primary > Open Modal!</Button >
            {showModal && modal}

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque justo et efficitur mattis. Nulla et quam justo. Curabitur tempus libero ut lacus mollis, pellentesque consectetur lectus porttitor. Vivamus non commodo nibh, nec porttitor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin dictum et dui pretium scelerisque. Curabitur venenatis urna ac augue euismod, bibendum consectetur lacus dapibus. Ut mattis lobortis interdum. Pellentesque aliquet leo tortor, eget faucibus magna congue a. Nulla facilisi. Praesent at ipsum mattis, scelerisque ante sit amet, sollicitudin augue. Fusce consectetur porta magna, mattis facilisis urna rhoncus ut.</p>
        </div >
    )
}

export default ModalPage